### ISSUE TITLE
Support for other Bitron video devices

### ISSUE THREAD

**Issue by mveck** [mhaid/de.mhaid.bitron#1]
I would like to discuss if it is possible to add more Bitron devices. Have access to smart switches, and door contacts. I managed to create support for the switch, but would love to have a single apo supporting all.
Prepared to share some code.

**Comment by mhaid** [comment]
Hello @mveck ,
Thanks for your comment.

We would be happy to add support for more Bitron devices to our app.
Please let us know when you are ready to share the code; of course you will be added as a contributor ;)

Best regards

**Comment by mveck** [comment]
Hi @mhaid Morris,
I will pull the branch and start merging my code. Currently I do have code for the smart-switch ready, and it runs fine as merged in 1.0.0

**Comment by mveck** [comment]
Hi Morris,
Just today I got a firmware update for Bitron Smartswitch. You would not
beleive that the changed something on the ID of the device. This means that
it works when people are running the old firmware, but it is not
recognizing the app support for the newer fw.
 I will work on this and keep you informed. (Just an update of the
app.json).

Cheers,
Menno



Op zo 16 jun. 2019 15:49 schreef Morris Haid <notifications@github.com>:
