### ISSUE TITLE
Update for Homey 2.0

### ISSUE THREAD

**Issue by Tequila329** [mhaid/de.mhaid.bitron#2]
Hi Guys, 

is there a update planed for Homey V2.0? 
Maybe including Bitron Zigbee devices? 

Best regards

**Comment by mhaid** [comment]
Hello @Tequila329 ,
Thanks for the comment.
We have updated the app to be compatible with Homey V2.x and are currently waiting for validation.

If any problems occur, please let us know.

Kind regards
