### ISSUE TITLE
IST-Temperatur in Device Kachel anzeigen 

### ISSUE THREAD

**Issue by joka222** [mhaid/de.mhaid.bitron#4]
Einen Änderungswunsch hätte ich. Wäre es möglich in der Device Kachel anstatt der Ziel-Temperatur die Ist-Temperatur anzuzeigen. Die Farbgebung kann so erhalten bleiben. Aus meiner Sicht wäre die Info über die Ist-Temperatur relevanter, wenn diese dann orange dargestellt wird, weiß man das noch auf eine Ziel-Temperatur geheizt wird und kann diese bei Bedarf recherchieren bzw. anpassen.

Denn dann muss man sowieso in die Einstellungen. Hätte auch den Vorteil, dass man in den Device Kacheln direkt die Temperatur von allen Räumen auf einen Blich sehen würde.

THX

**Comment by mhaid** [comment]
Die Kacheln sind in ihrem Aufbau von Athom festgelegt, jedoch hattest du schon einen Workaround gefunden, welches den _thermostat_mode_-Tag benötigt.

Wir haben für die neuste Version den Trigger _thermostat_mode aktualisiert_ hinzugefügt.
Nach einem Test, wird diese Version für alle zur Verfügung gestellt.

**Comment by mhaid** [comment]
Hallo Joka222,
um die Funktionalität des Triggers/Tags zu testen, kannst du die Testversion der App gerne einmal ausprobieren und uns eine Rückmeldung geben, ob alles korrekt funktioniert:
https://homey.app/en-au/app/de.mhaid.bitron/Bitron/test/

VG
Morris

**Comment by joka222** [comment]
Hallo Morris,

 

die neue Version 2.0.3 stürzt leider nach der Installation direkt ab. Und ist auch nicht neu startbar.

 

Fehler Log:

 



 

Viele Grüße

Jörg

 

 

Von: Morris Haid <notifications@github.com> 
Gesendet: Mittwoch, 8. Januar 2020 14:55
An: mhaid/de.mhaid.bitron <de.mhaid.bitron@noreply.github.com>
Cc: joka222 <mbslk@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [mhaid/de.mhaid.bitron] IST-Temperatur in Device Kachel anzeigen (#4)

 

Hallo Joka222,
um die Funktionalität des Triggers/Tags zu testen, kannst du die Testversion der App gerne einmal ausprobieren und uns eine Rückmeldung geben, ob alles korrekt funktioniert:
https://homey.app/en-au/app/de.mhaid.bitron/Bitron/test/

VG
Morris

**Comment by mhaid** [comment]
Hallo Jörg,

danke für dein Feedback.
Die Testversion der App wurde geupdated; wäre super wenn du diese erneut auf Funktionalität überprüfen könntest.
https://homey.app/a/de.mhaid.bitron/test/

Vielen Grüße
Morris

**Comment by joka222** [comment]
Hallo Morris,

 

die App stürzt jetzt nicht mehr ab. Soweit ok.

 

1.	Aber bei Änderung der Zieltemperatur < Isttemperatur wird der Modus in deiner App auf heizen gesetzt anstatt auf kühlen, d.h. die Farbe ist orange anstatt blau. Der Wandthemostat zeigt auch korrekt keine Flamme an.

 

2.	Darüber hinaus war es mir nicht möglich den themperatur_mode an das Virtuelle Device zu übergeben. Ob das ein Fehler deiner App ist oder des VD muss ich noch einmal testen.

 

Punkt 1 könntest du bitte einmal prüfen.

 

 

VG Jörg

 

 

Von: Morris Haid <notifications@github.com> 
Gesendet: Mittwoch, 8. Januar 2020 22:28
An: mhaid/de.mhaid.bitron <de.mhaid.bitron@noreply.github.com>
Cc: joka222 <mbslk@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [mhaid/de.mhaid.bitron] IST-Temperatur in Device Kachel anzeigen (#4)

 

Hallo Jörg,

danke für dein Feedback.
Die Testversion der App wurde geupdatet; wäre super wenn du diese erneut auf Funktionalität überprüfen könntest.
https://homey.app/a/de.mhaid.bitron/test/

Vielen Grüße
Morris

**Comment by mhaid** [comment]
Hallo Jörg,

ich habe den Code noch einmal überprüft und habe keinen Fehler gefunden.
Hoffentlich liegt es nicht an einem Fehler der Thermostat-Software, sondern doch im Code der App oder von Homey.

Weiterhin werde ich versuchen den Bug zu lokalisieren und die Neuerung funktionstüchtig zu machen.

Viele Grüße
Morris

**Comment by joka222** [comment]
Hallo Morris,

 

mit der Version 2.0.2 funktionierte die Farbgebung noch korrekt.

 

Meine weiteren Test haben ergeben, dass leider der Tag nicht an die Virtual Device Variable „Thermostat-Mode“ übergeben werden kann. Dies scheint aus meiner Sicht aber an dem Objekt Typ selbst zu liegen, d.h. nicht an deiner App, diese übergibt den Tag Thermostat-Mode (z.B. heat) korrekt. Der Objekt Typ des VDs nimmt aber leider nur explizit einen manuell eingetragen String (z.B. heat) an und keinen Tag.

 

Damit kann leider meine Anforderung nicht per Tag Übergabe realisiert, ich werde das dann per Logik über einen Vergleich der Soll-Ist-Temperaturen regeln und in der Action für den jeweiligen Fall den String eintragen.

 

Bedaure, dass du dir Arbeit gemacht hast, aber ggf. ist es in einem anderen Usecase dennoch sinnvoll den Tag Thermostat-Mode zu übergeben. Solltest du bzgl. der falschen Farbgebung noch den Fehler finden, teste ich dennoch gerne die neue Version auf ihre Funktionalität.

 

 

Viele Grüße

Jörg

 

 

 

Von: Morris Haid <notifications@github.com> 
Gesendet: Freitag, 10. Januar 2020 16:59
An: mhaid/de.mhaid.bitron <de.mhaid.bitron@noreply.github.com>
Cc: joka222 <mbslk@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [mhaid/de.mhaid.bitron] IST-Temperatur in Device Kachel anzeigen (#4)

 

Hallo Jörg,

ich habe den Code noch einmal überprüft und habe keinen Fehler gefunden.
Hoffentlich liegt es nicht an einem Fehler der Thermostat-Software, sondern doch im Code der App oder von Homey.

Weiterhin werde ich versuchen den Bug zu lokalisieren und die Neuerung funktionstüchtig zu machen.

Viele Grüße
Morris

**Comment by mhaid** [comment]
Hallo Jörg,

vielen dank für dein ausführliches Feedback.
Schade, dass die Tag-Übergabe nicht funktioniert hat. Der neue Workaround hört sich jedoch interessant an.

Da ich im Moment nicht zuhause bin, kann ich nicht selbst testen, ob der Tagthermostat-Mode Tag ("heating" oder "cooling") richtig ausgegeben wird. Es wäre sehr hilfreich, wenn du uns hier weiterhelfen könntest.

Wir werden natürlich weiterhin an der Verbesserung der App arbeiten und auch das Problem mit der Kachelfarbe (voraussichtlich) in der nächsten Version wieder beheben.

Viele Grüße
Morris

**Comment by mhaid** [comment]
### 1. Schließung des Issues

**Begründung**
Da von Athom eine Vorgabe der Device Kachel gegeben wird, die nicht anpassbar ist, kann der Vorschlag leider nicht umgesetzt werden.


### 2. Thermostat_Mode bzw. systemMode Problematik

Weiter wird mit der neuen Version der _thermostat_mode_ bzw. _systemMode_ wieder entfernt.

**Begründung**
Dies geschieht, um die standardmäßige automatische Erkennung des Modus von Homey zu nutzen. Die automatische Erkennung funktioniert problemlos und zeigt "kühlen" und "heizen" korrekt an.

**Auslöser des Problems**
Das ganze wird einzig durch das Problem ausgelöst, dass das Gerät AV2010/32 den _thermostat_mode_ bzw. _systemMode_: nicht automatisch ändert:
Das Thermostat betrachtet Heizen und Kühlen als zwei separate Funktionen mit eigenen Einstellungen. Es besitzt folgende Einstellungen:
1. Die Einstellung _controlSequenceOfOperation_ die festlegt, ob das Heizen und/oder Kühlen möglich ist
2. Die Einstellung _SystemMode_ die festlegt, ob das Heizen oder Kühlen aktiv ist
3. Die "Soll-Temperaturen" für das Heizen (occupiedHeatingSetpoint) und für das Kühlen (_occupiedCoolingSetpoint_)

Wenn nun das Kühlen aktiviert werden soll, muss zunächst sichergestellt werden, dass _controlSequenceOfOperation_ den Modus "Kühlen" erlaubt. Dann wird _systemMode_ manuell auf "Kühlen" gesetzt. Der letzte Schritt besteht aus dem Senden von _occupiedCoolingSetpoint_ mit der gewünschten Temperatur, da dieser nur gesetzt werden kann, wenn "Kühlen" als _systemMode_ aktiv ist.
_systemMode_ wird jedoch bei unterschreiten bzw. überschreiten der Soll-Temperatur nicht automatisch gändert.

**Zukünftige Handhabung**
Fall hier weiter  Bedarf am _thermostat_mode_ besteht, werden wir den _thermostat_mode_ implementieren und eine individuelle Lösung der Erkennung des Modus implementieren.
Eine Unterstützung der Aktivierung des "Kühlen" Relais des Thermostats haben wir mit der neusten Version implementiert. Das Feature kann in den Einstellungen eingeschaltet werden.
