### ISSUE TITLE
Wall thermostat 902010/32 doesn't send any value, error invalid device (Homey v5.0) 

### ISSUE THREAD

**Issue by joka222** [mhaid/de.mhaid.bitron#5]
With Homey v5.0 the device is reintegrated in the zigbee mesh correctly and visible. But it doesn't send any temperature value.

If I use the temperature wheel, I get ein error: invalid device.

**Comment by mhaid** [comment]
Hello Joka,
could you submit a crash report so I can have a closer look?

You can do that by navigation to the following menu in the Homey-App:
_More (Navigation bar on the bottom)-> Apps -> Bitron -> Setting-Symbol -> Create diagnostic report -> Enter some kind of text (min. 11-characters and not really relevant)_

Which app version do you have installed?

**Comment by joka222** [comment]
crash report:   21a355d1-cb0b-41c2-8f6d-3d707a395de0
app v3.0.4

**Comment by mhaid** [comment]
I just uploaded a new version (3.0.5). It will hopefully fix the issue.

https://homey.app/de-de/app/de.mhaid.bitron/Bitron/test/

**Comment by joka222** [comment]
no, I deleted and included the device again but issue still exist:

crash report: 5882ba6c-5f4a-4cb6-becf-decda64721ea
app v3.0.5

**Comment by mhaid** [comment]
Hey Joka,
I just uploaded a new version (3.0.6) which fixes the issue.
Please let me know if everything got back to normal :)
