### ISSUE TITLE
Request support for AV2010/34

### ISSUE THREAD

**Issue by hagdahl** [mhaid/de.mhaid.bitron#7]
I would like to request support for AV2010/34 wall breaker panel with four buttons
https://manuals.smabit.eu/len/av2010_34.html

Bitron AV2010/34 data:
Property | Value
ID | f357eb04-aff4-4d0c-b42a-92785bcce8fa
Class | socket
Driver | homey:manager:vdevice — zigbeebasic
Ready | Yes
Available | Yes
Warning | No
Custom icon | No
zb_product_id | "AV2010/34"
zb_manufacturer_name | "Bitron Video"
energy_alwayson | false
energy_value_off | null
energy_value_on | null
onoff | boolean | null

**Comment by mhaid** [comment]
Good afternoon,

I can implement the new device for you.
The infos are already helpful, but I do need more data on the clusters used by the device. As I do not have any 90210_34 devices, I can't get them myself.

Please visit "http://developer.athom.com/", login with your athom ID and then choose "Tools->Zigbee". Here you should find the switch-device listed. Next press "interview" and you should recieve the a listing of the used endpoints, clusters etc.
This is the info I would need for an implementation :)

Best regards,
Morris

**Comment by hagdahl** [comment]
Hi Morris
Thank you for you reply, this is the response for AV2010/34

`  "ids": {
    "modelId": "AV2010/34",
    "manufacturerName": "Bitron Video"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 4,
        "applicationProfileId": 260,
        "applicationDeviceId": 4,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 4,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          1,
          3
        ],
        "outputClusters": [
          3,
          4,
          5
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 0,
                "name": "zclVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 1,
                "name": "appVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 3,
                "name": "hwVersion"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 4,
                "name": "manufacturerName"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 5,
                "name": "modelId"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 6,
                "name": "dateCode"
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 7,
                "name": "powerSource"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 16,
                "name": "locationDesc"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 17,
                "name": "physicalEnv"
              },
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 18,
                "name": "deviceEnabled"
              }
            ]
          },
          "powerConfiguration": {},
          "identify": {}
        },
        "bindings": {
          "identify": {},
          "groups": {},
          "scenes": {}
        }
      },
      "4": {
        "clusters": {},
        "bindings": {
          "ota": {}
        }
      }
    }
  }`

**Comment by hagdahl** [comment]
The wall breaker panel came bundled with outlet plug dimmers Bitron / Smabit 902010/26
This is the response from them. They do already work with Homey, probably because they are very similar to the supported outlet plugs. I use them because it's one of the few zigbee outlet plugs that has dimmer functionality.


`  "ids": {
    "modelId": "902010/26",
    "manufacturerName": "Bitron Video"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 4,
        "applicationProfileId": 260,
        "applicationDeviceId": 257,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [],
        "outputClusters": [
          25
        ]
      },
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 257,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          3,
          4,
          5,
          6,
          8
        ],
        "outputClusters": [
          0
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {},
          "identify": {},
          "groups": {},
          "scenes": {},
          "onOff": {},
          "levelControl": {}
        },
        "bindings": {
          "basic": {}
        }
      },
      "4": {
        "clusters": {},
        "bindings": {
          "ota": {}
        }
      }
    }
  }`

**Comment by mhaid** [comment]
Hey David,
thank you for the logs.
I'll make a new app-version available to you soon (hopefully in the next few days)

Cheers,
Morris

**Comment by mhaid** [comment]
@hagdahl 
The new update got released today :)
It now supports a bunch of new devices
